#!/usr/bin/env python3
"""Build dist/ — the folder that actually gets deployed.

Copies the site's own files into dist/ and writes the Netlify _headers file
beside them. Nothing is minified or rewritten; dist/ is the same site with
the repo's working files (README, this script, .git) left behind.

    python3 build-dist.py

Drag dist/ onto app.netlify.com/drop, or let Netlify build from the repo —
netlify.toml points its publish directory at dist/, so both ship the same
bytes. Edit the files at the repo root, never the copies in dist/.
"""

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist"

# Everything the browser needs, and nothing else.
FILES = ["index.html", "menu.html", "robots.txt"]
DIRS = ["assets"]

# ── Response headers ───────────────────────────────────────────────────
#
# The site makes no third-party requests at all: no CDN, no analytics, no
# web fonts, no embeds. That means the Content-Security-Policy can be
# 'none' by default and allow only same-origin script, style, image and
# font — about as tight as a policy gets. Anything injected into the page
# has nowhere to load from and nowhere to phone home to.
#
# When the Google Maps embed goes in on the contact section, the policy
# needs one addition:
#
#     frame-src https://www.google.com;
#
# Add exactly that and nothing else.

CSP = "; ".join([
    "default-src 'none'",
    "script-src 'self'",
    "style-src 'self'",
    "img-src 'self'",
    "font-src 'self'",
    # the hero streams its own film with fetch(), then plays it from a Blob URL
    "connect-src 'self'",
    "media-src 'self' blob:",
    "form-action 'none'",
    "frame-ancestors 'none'",
    "base-uri 'none'",
    "object-src 'none'",
])

HEADERS = f"""# Netlify response headers. Applies to both drag-and-drop deploys and
# git-based builds, so long as this file sits in the published folder.
# Generated by build-dist.py — edit the script, not this file.

/*
  Content-Security-Policy: {CSP}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Robots-Tag: noindex, nofollow

# HTML and the two files most likely to be edited: always revalidate.
# Netlify sends an ETag, so an unchanged file still costs only a 304.
/*.html
  Cache-Control: public, max-age=0, must-revalidate
/assets/css/*
  Cache-Control: public, max-age=0, must-revalidate
/assets/js/*
  Cache-Control: public, max-age=0, must-revalidate

# Illustrations may be swapped for the client's photographs — a day is
# long enough to help and short enough not to strand anyone on old art.
/assets/img/*
  Cache-Control: public, max-age=86400

# The fonts never change. If one ever does, rename the file.
/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable
"""

# ── Going live ─────────────────────────────────────────────────────────
# While the site is a draft, `X-Robots-Tag: noindex, nofollow` above and
# `Disallow: /` in robots.txt keep it out of search results even if the
# URL leaks. Remove both when the client approves — see the README.
#
# `Strict-Transport-Security` is deliberately NOT set here. Netlify
# already serves HTTPS and redirects HTTP, and HSTS is very hard to undo
# once a browser has cached it. Add it at launch, on the real domain, and
# only when you are sure every subdomain can serve HTTPS.


def main() -> int:
    missing = [name for name in FILES + DIRS if not (ROOT / name).exists()]
    if missing:
        print("missing from the repo root: " + ", ".join(missing), file=sys.stderr)
        return 1

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir()

    for name in FILES:
        shutil.copy2(ROOT / name, DIST / name)
    for name in DIRS:
        shutil.copytree(ROOT / name, DIST / name)

    (DIST / "_headers").write_text(HEADERS, encoding="utf-8")

    total = 0
    count = 0
    for path in sorted(DIST.rglob("*")):
        if path.is_file():
            total += path.stat().st_size
            count += 1
            print(f"  {path.relative_to(DIST).as_posix():<38} {path.stat().st_size / 1024:7.1f} KB")

    print(f"\ndist/ — {count} files, {total / 1024:.0f} KB total")
    print("Drag dist/ onto https://app.netlify.com/drop")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
