#!/usr/bin/env python3
"""
Builds the Airmech Repairs site.

Static HTML in, static HTML out — there is no runtime dependency and Netlify
runs no build command. This exists only so the header, footer and shared
sections live in one place instead of five copies that drift apart.

    python3 build.py

Generated files carry a "do not edit" banner. Edit src/ and rebuild.
"""

import html
import json
import pathlib
import re
import shutil

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "src"
SITE = "https://airmechrepairs.com.au"
EMAIL = "Airmechrepairs@outlook.com.au"

BANNER = "<!-- Generated by build.py from src/ — edit the partials, not this file. -->\n"


def part(name):
    return (SRC / "partials" / f"{name}.html").read_text()


def sect(name):
    return (SRC / "sections" / f"{name}.html").read_text()


# ---------------------------------------------------------------- structured data

def ld(obj):
    return (
        '<script type="application/ld+json">\n'
        + json.dumps(obj, indent=2, ensure_ascii=False)
        + "\n</script>"
    )


BUSINESS = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": f"{SITE}/#business",
    "name": "Airmech Repairs",
    "alternateName": "Airmech Repairs — Airless Spray Equipment Repairs & Servicing",
    "description": "Diagnosis, repair, servicing and maintenance of airless spray equipment for painters, "
                   "decorators, maintenance contractors and construction professionals.",
    "url": f"{SITE}/",
    "email": EMAIL,
    "image": f"{SITE}/assets/img/og.jpg",
    "address": {
        "@type": "PostalAddress",
        "addressLocality": "Ocean Grove",
        "addressRegion": "VIC",
        "addressCountry": "AU",
    },
    "areaServed": [
        {"@type": "Place", "name": n}
        for n in ("Ocean Grove, Victoria", "Geelong, Victoria",
                  "Bellarine Peninsula, Victoria", "Surf Coast, Victoria")
    ],
    "knowsAbout": [
        "Airless spray gun repairs",
        "Airless spray equipment servicing",
        "Spray equipment fault finding",
        "Airless sprayer maintenance",
    ],
}

SERVICES = [
    ("Equipment Diagnosis", "Identify faults and determine what your equipment needs."),
    ("Repairs", "Professional repair work to get airless spray equipment operating correctly again."),
    ("Servicing & Maintenance", "Routine servicing and maintenance to help keep equipment performing reliably."),
    ("Fault Finding", "Investigating equipment problems and identifying the underlying issue."),
    ("Equipment Performance Checks", "Assessing equipment operation and identifying potential issues."),
]

SERVICE_CATALOG = {
    "@context": "https://schema.org",
    "@type": "OfferCatalog",
    "name": "Airless spray equipment services",
    "itemListElement": [
        {"@type": "Offer",
         "itemOffered": {"@type": "Service", "name": n, "description": d,
                         "provider": {"@id": f"{SITE}/#business"},
                         "areaServed": "Geelong and the Bellarine Peninsula, Victoria"}}
        for n, d in SERVICES
    ],
}


def crumbs(name, path):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
            {"@type": "ListItem", "position": 2, "name": name, "item": f"{SITE}{path}"},
        ],
    }


# ---------------------------------------------------------------- pages

def page_header(crumb, h1, intro):
    return (sect("page-header")
            .replace("{{crumb}}", crumb)
            .replace("{{h1}}", h1)
            .replace("{{intro}}", intro))


PAGES = [
    dict(
        out="index.html",
        path="/",
        nav="home",
        title="Airless Spray Equipment Repairs & Servicing | Airmech Repairs, Ocean Grove",
        description="Airmech Repairs services and repairs airless spray equipment for painters and contractors "
                    "across Ocean Grove, Geelong and the Bellarine Peninsula. Fast diagnosis, quality "
                    "workmanship, less downtime.",
        jsonld=[BUSINESS],
        body=["hero", "trust", "about", "services", "area", "cta"],
    ),
    dict(
        out="services/index.html",
        path="/services/",
        nav="services",
        title="Airless Spray Equipment Servicing & Repairs | Airmech Repairs",
        description="Diagnosis, repairs, servicing, fault finding and performance checks for airless spray "
                    "equipment. Graco and other major brands, serviced from Ocean Grove.",
        header=("Services",
                "Airless spray equipment <br>repairs &amp; servicing",
                "Diagnosis, repairs, routine servicing, fault finding and performance checks — for the airless "
                "spray equipment your work depends on."),
        jsonld=[SERVICE_CATALOG, crumbs("Services", "/services/")],
        body=["services-detail", "equipment", "process", "cta"],
    ),
    dict(
        out="about/index.html",
        path="/about/",
        nav="about",
        title="About Airmech Repairs | Airless Spray Equipment Specialists, Ocean Grove",
        description="Airmech Repairs specialises in diagnosing, servicing and repairing airless spray equipment "
                    "for painters, contractors and builders across Geelong and the Bellarine Peninsula.",
        header=("About",
                "Specialists in airless <br>spray equipment",
                "Built around trades and businesses that depend on reliable equipment — and lose money every "
                "hour it sits idle."),
        jsonld=[crumbs("About", "/about/")],
        body=["about", "why", "cta"],
    ),
    dict(
        out="service-area/index.html",
        path="/service-area/",
        nav="area",
        title="Spray Equipment Repairs Geelong & Bellarine Peninsula | Airmech Repairs",
        description="Airless spray equipment repairs and servicing across Ocean Grove, Geelong, the Bellarine "
                    "Peninsula and surrounding areas. Based in Ocean Grove, Victoria.",
        header=("Service Area",
                "Airless spray repairs across <br>Geelong &amp; the Bellarine",
                "Based in Ocean Grove and servicing professional customers throughout Geelong, the Bellarine "
                "Peninsula and the areas around them."),
        jsonld=[crumbs("Service Area", "/service-area/")],
        body=["area-full", "cta"],
    ),
    dict(
        out="contact/index.html",
        path="/contact/",
        nav="contact",
        title="Contact Airmech Repairs | Airless Spray Equipment Repairs, Ocean Grove",
        description="Contact Airmech Repairs about airless spray equipment repairs, servicing or maintenance. "
                    "Email Airmechrepairs@outlook.com.au — Ocean Grove, Geelong and the Bellarine Peninsula.",
        header=("Contact",
                "Contact Airmech Repairs",
                "Email through what you're running and what it's doing, and you'll get a straight answer on "
                "what's involved."),
        jsonld=[{"@context": "https://schema.org", "@type": "ContactPage",
                 "name": "Contact Airmech Repairs", "url": f"{SITE}/contact/",
                 "mainEntity": {"@id": f"{SITE}/#business"}},
                crumbs("Contact", "/contact/")],
        body=["contact-details", "cta"],
    ),
]


def render(p):
    head = part("head")
    head = (head
            .replace("{{title}}", p["title"])
            .replace("{{description}}", html.escape(p["description"], quote=True))
            .replace("{{site}}", SITE)
            .replace("{{path}}", p["path"])
            .replace("{{jsonld}}", "\n".join(ld(o) for o in p["jsonld"])))

    if p.get("noindex"):
        head = head.replace('<meta name="theme-color"',
                            '<meta name="robots" content="noindex, follow">\n<meta name="theme-color"')

    header = part("header")
    if p["nav"]:
        header = header.replace(f'data-nav="{p["nav"]}"', f'data-nav="{p["nav"]}" aria-current="page"')
        header = header.replace(f'data-dnav="{p["nav"]}"', f'data-dnav="{p["nav"]}" aria-current="page"')

    chunks = []
    if p.get("header"):
        chunks.append(page_header(*p["header"]))
    for name in p["body"]:
        chunks.append(sect(name))

    body = "\n".join(chunks)
    body = body.replace("{{map}}", sect("map"))

    return BANNER + head + header + "\n" + body + part("footer")


def main():
    for p in PAGES:
        out = ROOT / p["out"]
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render(p))
        print(f"  {p['out']:26} {out.stat().st_size / 1024:6.1f} KB   {p['path']}")

    urls = "\n".join(
        f"  <url>\n    <loc>{SITE}{p['path']}</loc>\n"
        f"    <changefreq>monthly</changefreq>\n"
        f"    <priority>{'1.0' if p['path'] == '/' else '0.8'}</priority>\n  </url>"
        for p in PAGES if not p.get("noindex")
    )
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{urls}\n</urlset>\n"
    )
    print(f"  {'sitemap.xml':26}          {sum(1 for p in PAGES if not p.get('noindex'))} urls")


if __name__ == "__main__":
    print("Building Airmech Repairs site")
    main()
    print("Done.")
